[rocks]
vusted = "2.3.4"

[plugins]
"rocks.nvim" = "2.35.0"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.1.3"
"haskell-tools.nvim" = "3.1.10"
"squirrel.nvim" = "1.0.0"

"rocks-treesitter.nvim" = "scm"

tree-sitter-cpp = "scm"
tree-sitter-fish = "scm"
tree-sitter-toml = "scm"
tree-sitter-json = "scm"
tree-sitter-latex = "scm"
tree-sitter-asm = "scm"
tree-sitter-zig = "scm"
tree-sitter-rust = "scm"
tree-sitter-scala = "scm"

[treesitter]
auto_highlight = "all"
auto_install = ["lua", "vim", "vimdoc", "query"]

[config]
plugins_dir = "plugins/"
auto_setup = false

# telescope stuff
[plugins.devicons]
git = "nvim-tree/nvim-web-devicons"
[plugins.plenary]
git = "nvim-lua/plenary.nvim"
[plugins.telescope]
git = "nvim-telescope/telescope.nvim"
[plugins.file_browser]
git = "nvim-telescope/telescope-file-browser.nvim"

# cmp stuff
[plugins.cmp]
git = "hrsh7th/nvim-cmp"
event = "InsertEnter"
[plugins.cmp-lsp]
git = "hrsh7th/cmp-nvim-lsp"
event = "InsertEnter"
[plugins.cmp-lsp-signature]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
event = "InsertEnter"
[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"
event = "InsertEnter"

[plugins.lspconfig]
git = "neovim/nvim-lspconfig"

[plugins.dap]
git = "mfussenegger/nvim-dap"

[plugins.hipatterns]
git = "echasnovski/mini.hipatterns"
event = "BufEnter"

[plugins.jtdls]
git = "mfussenegger/nvim-jdtls"
ft = "java"

[plugins.format-lint]
git = "nvimdev/guard.nvim"

[plugins.bad-apple]
git = "seandewar/bad-apple.nvim"
cmd = "BadApple"
