# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
fzy = "1.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.9.0"
"rocks-git.nvim" = "1.2.1"
nvim-dap = "0.7.0" 
"haskell-tools.nvim" = "3.1.6"
nvim-lspconfig = "0.1.7"
"squirrel.nvim" = "1.0.0"
nvim-nio = "1.7.0"

# telescope stuff that I will _eventually_ rewrite
[plugins.devicons]
git = "nvim-tree/nvim-web-devicons"
[plugins.plenary]
git = "nvim-lua/plenary.nvim"
[plugins.telescope]
git = "nvim-telescope/telescope.nvim"
[plugins.file_browser]
git = "nvim-telescope/telescope-file-browser.nvim"

[plugins.hipatterns]
git = "echasnovski/mini.hipatterns"

[plugins.treesitter]
git = "nvim-treesitter/nvim-treesitter"

[plugins.completion]
git = "nvimdev/epo.nvim"

[plugins.format-lint]
git = "nvimdev/guard.nvim"

[plugins.bad-apple]
git = "seandewar/bad-apple.nvim"
