[rocks]

[plugins]
"rocks.nvim" = "2.37.0"
"rocks-config.nvim" = "2.2.0"

"guard.nvim" = "scm"
"indentmini.nvim" = "scm"
"mini.hipatterns" = "0.9.0"
"squirrel.nvim" = "1.0.0"
nvim-lspconfig = "0.1.8"
"rocks-treesitter.nvim" = "1.0.3"
nvim-metals = "0.9.x"

tree-sitter-toml = "0.0.1"
tree-sitter-css = "0.0.1"
tree-sitter-json = "0.0.1"
tree-sitter-typescript = "0.0.1"

[config]
plugins_dir = "plugins/"
auto_setup = false
colorscheme = "moonlight"
